name: leanframe_app
description: Client for LeanFrame photo frame
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  mobile_scanner: ^6.0.2
  http: ^1.2.2
  file_picker: ^8.1.2
  photo_manager: ^3.2.1
  # color picker
  flutter_colorpicker: ^1.1.0
  wifi_iot: ^0.3.19+2
  permission_handler: ^11.3.1
  bonsoir: any
  path_provider: ^2.1.3
  crypto: ^3.0.3
  share_plus: ^10.0.0
  image: ^4.2.0

flutter:
  uses-material-design: true
